service: piatti-front-react

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  stage: ${opt:stage, 'prod'}
  bucketName: ${self:custom.stage}-piatti-front-react
  domainName: piatti-erp.com
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist/

resources:
  Conditions:
    isProd: !Equals ["${{param:stage}}","prod"]
  Resources:
    PiattiBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        # AccessControl: PublicRead
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    S3AccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: PiattiBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: 
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::${self:custom.bucketName}/*
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          CNAMEs:
            - "${self:custom.domainName}"
          Origins:
            - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
              #OriginPath: "/index.html"
              Id:   ${self:custom.stage}-piattiAPP
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginKeepaliveTimeout: 5
                OriginReadTimeout: 30
            - DomainName: ${self:custom.bucketName}.s3-website-us-east-1.amazonaws.com
              #OriginPath: "/index.html"
              Id:   ${self:custom.stage}-piattiAPP-website
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginKeepaliveTimeout: 5
                OriginReadTimeout: 30
          Enabled: true
          Aliases:
            - "${self:custom.domainName}"
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId:  ${self:custom.stage}-piattiAPP
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:895047112900:certificate/623b6d62-78a9-46de-a3a1-6b7fddf70f77
            SslSupportMethod: sni-only
          HttpVersion: http2